import os
import uuid
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
import pandas as pd
from typing import List, Dict, Any
from app.core.config import settings

class DocIntelligenceTool:
    def __init__(self):
        self.name = "doc_intelligence"
        self.description = "Generate professional Word (.docx), PowerPoint (.pptx), or Excel (.xlsx) files from text or data."
        self.output_dir = os.path.join(os.getcwd(), "exports")
        os.makedirs(self.output_dir, exist_ok=True)

    def execute(self, action: str, content: str, title: str = "ASTRA_Export", format: str = "docx") -> str:
        """
        Actions: 'create_report', 'create_presentation', 'create_table'
        Format: 'docx', 'pptx', 'xlsx'
        """
        filename = f"{title.replace(' ', '_')}_{uuid.uuid4().hex[:6]}.{format}"
        file_path = os.path.join(self.output_dir, filename)

        try:
            if format == "docx":
                return self._generate_docx(file_path, title, content)
            elif format == "pptx":
                return self._generate_pptx(file_path, title, content)
            elif format == "xlsx":
                return self._generate_xlsx(file_path, content)
            else:
                return f"Unsupported format: {format}"
        except Exception as e:
            return f"Error generating document: {str(e)}"

    def _generate_docx(self, file_path, title, content):
        doc = Document()
        doc.add_heading(title, 0)
        doc.add_paragraph(content)
        doc.save(file_path)
        return f"Successfully generated Word document: {os.path.basename(file_path)}"

    def _generate_pptx(self, file_path, title, content):
        prs = Presentation()
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by ASTRA OS Intelligence"

        # Content Slides (split by double newline or bullets)
        points = [p.strip() for p in content.split('\n') if p.strip()]
        for point in points[:10]: # Limit to 10 slides for MVP
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = "Analysis Insight"
            slide.placeholders[1].text = point

        prs.save(file_path)
        return f"Successfully generated PowerPoint deck: {os.path.basename(file_path)}"

    def _generate_xlsx(self, file_path, content):
        # Expecting CSV-like or JSON-like string for table
        try:
            import json
            data = json.loads(content)
            df = pd.DataFrame(data)
        except (json.JSONDecodeError, ValueError, TypeError, KeyError):
            from io import StringIO
            df = pd.read_csv(StringIO(content))
        
        df.to_excel(file_path, index=False, engine='openpyxl')
        return f"Successfully generated Excel sheet: {os.path.basename(file_path)}"
